apiVersion: batch/v1
kind: CronJob
metadata:
  name: itsbeginningtolookalotlikechristmas-datagather
spec:
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      backoffLimit: 2
      template:
        metadata:
          labels:
            app: itsbeginningtolookalotlikechristmas-datagather
        spec:
          restartPolicy: Never
          containers:
            - name: itsbeginningtolookalotlikechristmas-datagather
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              env:
                - name: SPOTIFY_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: spotify-credentials
                      key: client_id
                - name: SPOTIFY_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: spotify-credentials
                      key: client_secret
                - name: GITHUB_APP_ID
                  valueFrom:
                    secretKeyRef:
                      name: evoteumbot
                      key: app_id
                - name: GITHUB_APP_PRIVATE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: evoteumbot
                      key: private_key
                - name: GIT_USER_NAME
                  value: {{ .Values.git.user.name | quote }}
                - name: GIT_USER_EMAIL
                  value: {{ .Values.git.user.email | quote }}
