apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spotify-credentials
spec:
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: spotify-credentials
  data:
    - secretKey: client_id
      remoteRef:
        key: itsbeginningtolookalotlikechristmas/spotify
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: itsbeginningtolookalotlikechristmas/spotify
        property: client_secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: evoteumbot
spec:
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: evoteumbot
  data:
    - secretKey: app_id
      remoteRef:
        key: platform/evoteumbot
        property: app_id
    - secretKey: private_key
      remoteRef:
        key: platform/evoteumbot
        property: ssh_privatekey
